const themes = {
  base: {
    a: '#ffffffff',
    b: '#ffffffff',
    c: '#ffffffff',
    d: '#ffffffff',
    e: '#ffffffff',
    f: '#ffffffff',
    g: '#ffffffff',
    h: '#ffffffff',
    i: '#ffffffff',
    j: '#ffffffff',
  },
  'pink-sunflower': {
    a: '#ffc331ff',
    b: '#ffd145ff',
    c: '#ffde59ff',
    d: '#ffd379ff',
    e: '#ffc798ff',
    f: '#ffb198ff',
    g: '#ffafd7ff',
    h: '#ffb0b8ff',
    i: '#f07d81ff',
    j: '#e04969ff',
  },
  'mean-pinky': {
    a: '#e2a4ffff',
    b: '#f1d2ffff',
    c: '#ffffffff',
    d: '#e86aa7ff',
    e: '#ba6fd3ff',
    f: '#8b73ffff',
    g: '#c58eeeff',
    h: '#ffa8dcff',
    i: '#fcc9eeff',
    j: '#f8eaffff',
  },
  'night-light': {
    a: '#bb63bfff',
    b: '#6123a8ff',
    c: '#4d338fff',
    d: '#9aa8e6ff',
    e: '#97a5fcff',
    f: '#67d4f5ff',
    g: '#0fbbf5ff',
    h: '#4466fcff',
    i: '#394ab8ff',
    j: '#0410bfff',
  },
};

module.exports = themes;
